### ISSUE TITLE
iOS build do not work anymore

### ISSUE THREAD

**Issue by jvernet** [mauiaaron/apple2#18] opened 2016-05-15 16:41 UTC
Hi,

Here is what I have when trying to build for iOS:

/Users/jeromevernet/Documents/dev/Github/apple2/src/x86/cpu-regs.h:155:13: Unsure of __PIC__ code on i386 Mac
/Users/jeromevernet/Documents/dev/Github/apple2/src/darwin-cpu-glue.S:20:17: In file included from /Users/jeromevernet/Documents/dev/Github/apple2/src/darwin-cpu-glue.S:20:
/Users/jeromevernet/Documents/dev/Github/apple2/src/x86/cpu.S:16:10: In file included from /Users/jeromevernet/Documents/dev/Github/apple2/Apple2Mac/../src/x86/cpu.S:16:

**Comment by mauiaaron** [comment] 2016-05-16 01:41
I just pushed 2 commits to develop branch that get Apple2ix building for the iOS simulator.  It appears to boot, but functionality is limited due to changes to the `prefs.h`.

I don't have time this month to work on the iOS version since I am working at a new job.

If you want to fix it yourself, the preferences for most modules now need to be set by JSON (`$HOME/.apple2.json`).

**Comment by mauiaaron** [comment] 2016-05-16 01:43
Example of the new `.apple2.json` file for setting and saving preferences (some of these settings are Android-specific and can be ignored):
```JSON
{
	"interface" : {
		"emulatorVersion" : 18,
		"landscapeEnabled" : true,
		"deviceWidth" : 2392,
		"deviceHeight" : 1440,
		"glVendor" : "Qualcomm",
		"glRenderer" : "Adreno (TM) 420",
		"glVersion" : "OpenGL ES 3.1 V@127.0 (GIT@I8366cd0437)",
		"diskAnimationsEnabled" : true,
		"sendCrashReports" : true
	},
	"touchscreen" : {
		"screenOwner" : 1,
		"isCalibrating" : false
	},
	"vm" : {
		"cpuScale" : 100,
		"driveAInsertedDisk" : "\/storage\/emulated\/0\/apple2ix\/lady_tut.dsk",
		"driveAInsertedDiskRO" : false,
		"driveBInsertedDisk" : "",
		"driveBInsertedDiskRO" : false,
		"diskPathStack" : [ "\/storage\/emulated\/0\/apple2ix" ],
		"driveACurrent" : true
	},
	"joystick" : {
		"jsTapDelaySecs" : 0.1,
		"jsSwipeNorthChar" : 0,
		"jsSwipeSouthChar" : 2,
		"jsTouchDownChar" : 1,
		"kpPresetChoice" : 2,
		"screenDivider" : 0.65,
		"showControls" : true,
		"axisIsOnLeft" : true,
		"axisSensitivity" : 0.75,
		"switchThreshold" : 144,
		"kpAxisRosetteChars" : [ "191", "65", "191", "136", "191", "149", "191", "90", "191" ],
		"kpAxisRosetteScancodes" : [ "-1", "30", "-1", "105", "-1", "106", "-1", "44", "-1" ],
		"kpTouchDownChar" : 177,
		"kpTouchDownScancode" : 57,
		"kpSwipeSouthChar" : 191,
		"kpSwipeSouthScancode" : -1,
		"kpSwipeNorthChar" : 191,
		"kpSwipeNorthScancode" : -1,
		"keyRepeatThresholdSecs" : 0.2
	},
	"keyboard" : {
		"touchMenuEnabled" : true,
		"portraitHeightScale" : 0.53,
		"portraitPositionScale" : 0.05,
		"keyClickEnabled" : true,
		"minAlpha" : 0.1,
		"maxAlpha" : 0.9,
		"lowercaseEnabled" : false,
		"glyphMultiplier" : 2,
		"altPathIndex" : 1,
		"altPath" : "\/storage\/emulated\/0\/apple2ix\/conan.kbd.json"
	},
	"video" : {
		"portraitPositionScale" : 0.75,
		"colorMode" : 2
	},
	"audio" : {
		"speakerVolume" : 6,
		"mbEnabled" : true,
		"mbVolume" : 3,
		"audioLatency" : 0.25
	}
}
```

**Comment by mauiaaron** [comment] 2016-07-09 17:54
Confirmed device build for ARM is broken by the recently changed __PIC__ codepaths introduced for Android.  Working on Apple/Darwin-specific fixes.

**Comment by mauiaaron** [comment] 2016-07-25 01:37
Believe this is fixed in latest develop.  Tests appear to be working.  Feel free to re-open if you see further problems.

**Closed by mauiaaron** 2016-07-25 01:37 UTC
Labels: bug
